[package]
name = "mongo_example_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.0.2"
tokio = "1.13.0"
serde = { version = "1.0", features = ["derive"] }
futures = "0.3"
