apiVersion: v1
kind: Pod
metadata:
  name: multiline-log-pod
spec:
  containers:
  - name: multiline-log-container
    image: alpine:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo -e 'Line 1\nLine 2\nLine 3'; sleep 5; done"]
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"
  restartPolicy: OnFailure
