[package]
name = "template-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
log = "0.4.22"
env_logger = "0.11.3"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
